export const CHANGE_LEFT_COL_PERC_GOAL = 'CHANGE_LEFT_COL_PERC_GOAL' 
export const CHANGE_READER_HEIGHT_GOAL = 'CHANGE_READER_HEIGHT_GOAL' 


export const FIRST_THROW = 'FIRST_THROW'
export const TOGGLE_PROJECT_SELECTION = 'TOGGLE_PROJECT_SELECTION'
export const CHANGE_ALL_PROJECT_SELECTION = 'CHANGE_ALL_PROJECT_SELECTION'
export const TOGGLE_READER_HEIGHT = 'TOGGLE_READER_HEIGHT'
export const SET_READER_TEXT= 'SET_READER_TEXT'
