export const CHANGE_WINDOW_DIMS = 'CHANGE_WINDOW_DIMS' 

export const CHANGE_LEFT_COL_PERC_GOAL = 'CHANGE_LEFT_COL_PERC_GOAL' 
export const CHANGE_READER_HEIGHT_GOAL = 'CHANGE_READER_HEIGHT_GOAL' 

export const CHANGE_ACTIVE_TAB = 'CHANGE_ACTIVE_TAB' 


export const CHANGE_READER_CONTENT = 'CHANGE_READER_CONTENT'


export const TOGGLE_VIZ_SETTINGS = 'TOGGLE_VIZ_SETTINGS'

